### ISSUE TITLE
Using LevelGenerator to place chunks created from other assets.

### ISSUE THREAD

**Issue by VoidFletcher** [Moolt/LevelGenerator#3]
Good day, Moolt!

Level generator looks incredibly powerful, however, there seems to be a lack of documentation on how to actually use it. I'd like to build a room from assets (setting the "entrance" as a "door") and save the prefab as a chunk. I seem to have an issue doing that though. I also cannot seem to assign any fuzzy tags to the chunk.

Also another note, window > node editor, seems to have no functionality? 

Would really love to get this running, any help would be greatly appreciated - and I'd be more than happy to help out with documentation once I understand the system a bit better.

Thanks!

Unity 2017.2.0f3
![image](https://user-images.githubusercontent.com/10835605/43282360-370903bc-9116-11e8-877e-22428e3e9fc9.png)

**Comment by Moolt** [comment]
Hi, I'm currently working on a documentation. It will be done in a few days.

1. As I can see on the screenshot, you are using the plugin differently from what it is intended to do.
The room and hallway meshes are being generated automatically, so usually you should not build statically sized rooms with assets for walls. Theoretically it's possible, but not recommended and it would be more simple to program something like this from scratch.

2. What problems occur when you try to save chunks?

3. Fuzzy tags cannot be assigned directly, they are calculated automatically. A scene with many lights will result in the fuzzy tag "Lighting" to have the value "Bright". If you want to set tags by yourself, add user defined tags.

4. The node editor has never been implemented and is therefore useless, yes.

**Comment by VoidFletcher** [comment]
Hi Moolt! Thanks for getting back to me.

What I'm trying to do is to strip away the wall and door mesh generation, and build the chunks up from assets, with the "door" location being open. I figure the library is more for level prototyping, but theoretically should be able to choose from predefined sets of assets that make up a chunk prefab, and then link those chunks together? Or am I misunderstanding?

I can save the chunk without issue, but attempting to "load" the asset throws an array out of bounds I think, I'll check for you in the morning as I'm about to head off to sleep. Also generating random levels doesn't ever use the saved chunk. Does the saved prefab have to be in the same folder as the other prefabs? Or does it search all assets for the chunk tag?

My goal would be to create the above mentioned rooms from assets. Then label them, like "Zone: x", "Enemies: x" but user defined tags don't seem to have the same functionality as fuzzy tags.

Apologies if any of this seems a bit stupid or is not supported, I'm just trying to figure out how much of this is possible. I'm glad to hear there are documents being made, that will help a ton!

**Comment by Moolt** [comment]
1. Yes, this is possible. You can't really replace the mesh of the generated hallways, though - at least it will be a whole lot of work.

2. Loading and saving chunks should only be managed by the ``Chunk and hallway manager``.  Don't manually drag and drop chunks into the scene. Chunks also should be placed in the "Resources/ProceduralGeneration/Chunks/" folder, else they will not be found by the generator.

@Tags: In this case, you can implement your own fuzzy tag, which is quite easy. You have to create a new class overriding the ``DynamicTag`` class and implement InterpolationValue() to return a value between 0 and 1, like in the example.

```cs
public class EnemyTag : DynamicTag
{
    protected override float InterpolationValue()
    {
        int amount = GameObject.FindGameObjectsWithTag("Enemy").Length;
        float smallestValue = 0;
        float highestValue = 10;
        return Mathf.InverseLerp(smallestValue, highestValue, amount);
    }
}
```
Then you have to open the dynamic tags editor, where you have to add a new tag with the attributes you want, like "safe", "medium", "dangerous" etc. The attribute has to have the same name as the class, in this case name it ``Enemy``. That's all, the tag will now appear in the Chunk tags and will be automatically calculated.

**Comment by VoidFletcher** [comment]
Hi Moolt!

Thanks again for getting back to me. I've saved the chunk prefabs to the correct folder and the level generator is now using my custom chunks in its generation (Basically by disabling any visual components and colliders associated with the chunks). I am however having an odd situation where having multiple doors on a chunk, the extra doors don't get used (as below), so as soon as I try generate 3 rooms or more, it no longer generates anything.

![image](https://user-images.githubusercontent.com/10835605/43365754-005b791c-9332-11e8-96c4-4a6e4d23a44c.png)
EDIT: The above chunks have "doors" on the bottom sections of the above image that are not being used.

Whoo hoo! So now I'm at the point where I'd need to either strip the hallways, or create several hallway prefabs. I have created a hallway with 2 entrances, but it doesn't seem to use it in generation.

Another workaround for the hallways would be to strip them out entirely. Do you have any idea how I could go about forcing rooms to "spawn connected"? That way I could create chunks that act as hallways with their own custom meshes.

Great work with Level Generator so far! It deserves WAAAAAY more attention.

EDIT 2: Regarding the fuzzy tags, that's a brilliant implementation, I'll definitely be creating a bunch of those. Thank you for the help!

**Comment by Moolt** [comment]
You have to explicitly define doors in the Door Manager component of the chunk. You only have one door defined on the chunk. Therefore two rooms can be connected with each other, but it's impossible with three or more - the log should also print an error message accordingly.

But if you define more doors you will run into another problem - a similar one like you have in your screenshot. Two rooms will usually only be connected by one single corridor. Any leftover doors will lead to a crash if they cannot be connected to a door of another room. That's why the Door Manager has a ``Min Quantity`` and ``Max Quantity`` option, to let the plugin decide how many doors are actually needed.

If you use the built in mesh generation, unused doors will simply not appear in the room mesh and will look like regular walls. In your case, even doors that are not used during generation will be visible to the player as a hole. The solution to this problem would be creating a wall tile even at positions that should lead to a hallway, and link this wall tile to the door defined in the door manager. This is further explained in this video: https://youtu.be/P2rAnXnNdSI?t=283

If your hallway mask is not used in generation, please check whether it is placed under ``Resources\ProceduralGeneration\Hallways``.

Removing hallways completely is impossible, sadly so. You'd have to change a bunch of code to achieve this.

Thanks for the kind words. However, I think you'd profit from writing your own level generator after testing out this plugin. You have some very specific ideas the generator hasn't been built for so you might run into a lot of dead ends and frustration. Procedural content generation is also very fun to code ;)

**Comment by VoidFletcher** [comment]
I had assigned the doors, but forgot to increase the max door count. It's now generating the rooms correctly:

![image](https://user-images.githubusercontent.com/10835605/43367735-5472f24e-9352-11e8-8598-3c59e8174e70.png)

Also my screenshots may appear misleading, the walls in the images go down, to achieve this effect (Screenshot from a build not using procedural gen):

![image](https://user-images.githubusercontent.com/10835605/43367770-ba6746fe-9352-11e8-9b94-16d547d550e3.png)

Regarding hallways masks, I assume they function similarly to chunks? Just in this case, marking a side as red means no connection possible? 

![image](https://user-images.githubusercontent.com/10835605/43367830-7e5c1828-9353-11e8-993c-c9cb291d0794.png)

The only problem with coding a generator myself is that my coding skills are not exceptional, however, I'm sure I could learn a lot from this system. I'm currently working solo on this.

EDIT: Also on a side note, after importing your plugin, clicking on some of my assets now causes these weird yellow lines that I've never seen before and the only other person who's had this issue on google closed the question and said they came right, never HOW they came right.

![image](https://user-images.githubusercontent.com/10835605/43367876-4afe4c98-9354-11e8-9aa5-39fda490da9b.png)

These yellow lines are incredibly unoptimised and I'm trying to figure out if it's just a coincidence that they are appearing around the time of import.

**Comment by Moolt** [comment]
Yup, hallways are very similar, but have a very important difference. While levels are made up of chunks, hallways are generated and then simply filled with the contents of your masks afterwards. Hallway mesh generation itself does **not** take your hallway masks into account. 
Hallways are generated as segments - if the mesh gizmo is still activated and you click on a hallway, this 
becomes visible. After the hallway meshes have been generated, your hallway masks are matched at every single segment - much like a puzzle. And if a mask fits at a certain position, it's contents are added to the scene.
The mask you've created looks for a straight hallway that is three segments long and has no other segments to the side. It's very unlikely that a mask like this will match, because hallways often have corners or junctions and may be shorter than three straight segments. You should keep your masks as simple as possible, like in the example:

![hallway masks](https://user-images.githubusercontent.com/5003354/43368138-bc6b1722-9358-11e8-94e3-0f9acb8d1a61.png)

But even then, it's hard to take every possible constellation into account.

The yellow lines are a new Unity feature, I guess. You can turn them off at the top of the scene editor via Gizmos -> Mesh Filter.

**Comment by VoidFletcher** [comment]
Okay, so theoretically it would be possible to have a "hallway" with no visible walls, and the floor could be built by being filled with floor assets? If this is the case then this should work perfectly for what I am trying to achieve.

So I've went and created several masks as per your image - with the inclusion of a 3 way junction. They are saved in Resources>ProceduralGeneration>Hallways

I've went and renamed the template extension to .bak so the only hallways the generator should detect is the ones I have just made. Yet, I am still getting pink hallways which are not being filled with the "floor".

![image](https://user-images.githubusercontent.com/10835605/43368557-591b2bba-935f-11e8-9206-52e4ec054258.png)

I'm just trying to figure out what I am missing. They aren't appearing in play mode either.

Picture:
![image](https://user-images.githubusercontent.com/10835605/43368570-9631f9d4-935f-11e8-9048-ab2a00038c29.png)

Also regarding the mesh filter gizmo, you are a life saver :'D

**Comment by Moolt** [comment]
Oops, I forgot to mention: Every hallway mask has a child object called ``Abstract Bounds``. Your walls should be direct children of this object, if you want them to be instantiated. Impossible to know without documentation, sorry.

**Comment by VoidFletcher** [comment]
Whooo hoo! Not a problem at all, atleast this will serve as a good reference when writing the documentation.

Moved the floor to be a child of `Abstract Bounds` and now it's partially working. The corner hallways are now appearing with "floors". But for some reason, the rest of the hallway isn't being populated with the one straight segment.

![image](https://user-images.githubusercontent.com/10835605/43368926-0f390296-9365-11e8-9e5e-410c17b344f0.png)

Disabling the mesh renderer on the `Hallways` gameobject gets rid of the pink.

![image](https://user-images.githubusercontent.com/10835605/43368963-e8a72436-9365-11e8-90a9-6445fe434748.png)

So my guess is I would possibly need a straight segment that is 2, 3, 4 and maybe 5 segments long? But as far as I understand from your explanation, having a single straight segment, should be enough to build up the hallway along the straight parts?

**Comment by Moolt** [comment]
> Disabling the mesh renderer on the Hallways gameobject gets rid of the pink.

You make it sound like a bug ;) 

>  having a single straight segment, should be enough to build up the hallway along the straight parts? 

Yes, this should already work. 
To be honest, I don't really know why it won't show up. I tried it just now and it worked fine.

**Comment by VoidFletcher** [comment]
Ahahaha it's not a bug, it's a feature :P .... that I do not need.

That's odd... I'll play around and build it from the template again. 

Thanks again for all the help Moolt! I'll fiddle around some more in the morning and see if I can come right.

EDIT: AYYYYYYY!!!!!!!!!!!!!!!!!!! It's working!!!!!!!!!! I was an idiot and had a test prefab that was being used instead. Deleted that and now it's using the correct one.

![image](https://user-images.githubusercontent.com/10835605/43369254-12b01f44-936b-11e8-9c51-890a3bda6c0d.png)

Edit 2: Is there a way to disable mesh renderer on Hallway? Alternatively I'll write a script to take care of that, not a problem :D

**Comment by Moolt** [comment]
> Is there a way to disable mesh renderer on Hallway? 

Nope, you'd have to write a script for that.

**Comment by VoidFletcher** [comment]
Cool! Thanks again for the help! I'll mark as closed and open another issue if I do come across any.
