### ISSUE TITLE
hallways are overlapping into chunks instead of meeting at the edge.

### ISSUE THREAD

**Issue by VoidFletcher** [Moolt/LevelGenerator#4]
Good evening Moolt!

Making some great progress here, now it's just a matter of polishing the connections. As you can see in the image below, the hallways are overlapping into the chunks. Meaning the center of the hallways is connecting with the chunk door, instead of the designated edge of the hallway template.

![image](https://user-images.githubusercontent.com/10835605/43542832-69254ae2-95ce-11e8-8e59-f80078d35d57.png)

So instead of following the blue path, it's following the red path. Meaning the designated edges (marked in green) are facing the wrong direction completely.

Any help would be much appreciated!

Making some great progress! 

![image](https://user-images.githubusercontent.com/10835605/43543184-7bc0e1a6-95cf-11e8-9c59-b0087c90f386.png)

**Comment by Moolt** [comment]
It looks like the generator assumes your rooms are smaller than they actually are.
Load your chunk and enable the mesh generation (in case it was disabled). Then take a look at the ``Abstract Bounds`` component. Since you don't want a random size, it should be fixed. Now adjust the size so, that the mesh overlaps perfectly with your assets. Now you can disable the mesh again.
This should already do the trick for your first problem.

The next problem - the segment at the door that is overlapping with the room - can only be fixed on my side, I guess. If you enable the grid in the debug options, you can see why. The segments are instantiated correctly, but in case of the segment at the door, it should only be half as big. Right now there is no way of telling a hallway mask that it should only match when it's neighboring a door segment.

If you want, I can look into it and add this particular feature. What you're creating looks really stunning, so I'd like to support you, if I find the time.

**Comment by VoidFletcher** [comment]
Thanks again for the speedy response, Moolt!

My abstract bounds are currently set to fixed and overlap near perfectly with the assets. 

Chunk Example:
![image](https://user-images.githubusercontent.com/10835605/43548283-d41ee43e-95dd-11e8-950e-ce67896f79fb.png)

Hallway Example:
![image](https://user-images.githubusercontent.com/10835605/43548340-f60d8636-95dd-11e8-821e-b84bdf90dec9.png)

A thought that just occurred to me, is that my corner hallway looks like:

![image](https://user-images.githubusercontent.com/10835605/43548410-20e7b8cc-95de-11e8-8870-78b53322ce34.png)

But as per your earlier recommendation, I should keep the hallway parts as simple as possible, I do not yet have a hallway component that looks like:

![image](https://user-images.githubusercontent.com/10835605/43548479-43630834-95de-11e8-92e0-00360a70003a.png)

So it could be possible that's why the entrances are not facing the correct way. I'll create that hallway mask now and give it another try and we can take it from there.

Thanks for the kind words, but it truly wouldn't be possible without your system.

**Comment by Moolt** [comment]
Your masks are not really the problem. I looked at an older screenshot of yours. The hallways are generated on a grid by connecting two blue nodes with each other on **the shortest path**. The reason why I assumed your Abstract Bounds are to small is because the nodes I marked with red should not even exist and therefore should not be considered for hallway generation. If you, somehow, get rid of these nodes, then the green path will be used instead. So I think experimenting with the chunk's Abstract Bounds is the way to go.
![nodes](https://user-images.githubusercontent.com/5003354/43549316-8d2825c4-95e0-11e8-94b1-8269d30d881d.PNG)

**Comment by VoidFletcher** [comment]
Okay so I've created the shortened corner:

![image](https://user-images.githubusercontent.com/10835605/43549317-8d360ce8-95e0-11e8-8c80-59033fe54432.png)

And in some situations, it is using the corer correctly, **but not in all cases**:

![image](https://user-images.githubusercontent.com/10835605/43549367-aeca8da2-95e0-11e8-8feb-c1d6666ee711.png)

Still no clue on how to fix the room connections, theoretically I could create offset hallways with no rotation, then rotate for all four rotations. But even then, that might not work.

Looking at the debug grid:

![image](https://user-images.githubusercontent.com/10835605/43549523-2265a3a0-95e1-11e8-818b-9d2c72ae4ad9.png)

It appears the connecting "point" of the grid is not on the edge of the hallway, but instead it's in the middle? WAIT! That means, I MIGHT be able to extend the hallway by 1 allowed chunk to forcefully offset it. But again, that wouldn't work in all situations.

Hmmmm, any ideas?

**Comment by VoidFletcher** [comment]
AHHH Like such!

![image](https://user-images.githubusercontent.com/10835605/43549737-beae112a-95e1-11e8-9aae-c742f4c812e9.png)

What do the blue cubes represent? Perhaps you created those as the connection points?

**Comment by Moolt** [comment]
> What do the blue cubes represent? Perhaps you created those as the connection points?

This indicates where this mask expects a hallway segment. It's easier to understand if you don't turn off the mesh for the hallway mask. The mesh of the mask is only an indicator and won't affect the actual hallway mesh anyway.

I think you misunderstood an essential part of hallway masks: They won't affect how hallways are generated. Not at all. First the hallways are generated and only then the masks are used to fill these hallways with content.

For now, you should concentrate on getting rid of these nodes I marked with red in the previous screenshot so the generator won't use these for hallway generation.

Edit: For debugging purposes it would also be useful to turn the meshes of the chunks back on.

**Comment by VoidFletcher** [comment]
Thanks, I nearly missed your post with the red lines.

So I've increased the abstract bounds, and extended a sort of a ramp out to the chunk door. The result is as follows:

![image](https://user-images.githubusercontent.com/10835605/43551593-d6e01ada-95e7-11e8-9f2e-d81e99714b05.png)

This sadly seems to be confirming my theory that the center of the hallway is what is snapping to the "door" instead of the edge of the hallway.

So I'm stumped.

EDIT: Also thank you for the clarification on how the hallway generation works.

EDIT 2: Some screenshots with the chunk mesh renderer enabled.

![image](https://user-images.githubusercontent.com/10835605/43553007-553931be-95ed-11e8-88f9-b3deecf2b7ee.png)

![image](https://user-images.githubusercontent.com/10835605/43553019-63a98f5a-95ed-11e8-8a32-e2d29a7af4a6.png)

**Comment by Moolt** [comment]
> This sadly seems to be confirming my theory that the center of the hallway is what is snapping to the "door" instead of the edge of the hallway.

Yes, that's true. That's why I said:

>  the segment at the door that is overlapping with the room - can only be fixed on my side, I guess. If you enable the grid in the debug options, you can see why. The segments are instantiated correctly, but in case of the segment at the door, it should only be half as big. Right now there is no way of telling a hallway mask that it should only match when it's neighboring a door segment.

And for the other problems I would need to take look at your project directly as it's really hard to guess where the problem is at this point. Maybe you could strip you project from all resources you don't want to share and send me a copy so I can look into it.

**Comment by VoidFletcher** [comment]
Ahhh okay, thanks for the clarification. 

If you do have some time and the motivation to work on fixing the hallway overlap, it would be GREATLY appreciated. However, from a logical perspective, it seems like it's going to be quite a challenging fix. The only way I could think of right off the bat, is you would have to create a sub-grid on the main grid and have a snap point on the edge of the hallways for connecting hallways to the main grid (you could theoretically use this for detecting which side a hallway is connected to a room.

Excuse the really shitty sketch,

![image](https://user-images.githubusercontent.com/10835605/43608430-5912827c-96a1-11e8-9fd3-ca1c7f610f15.png)

So yeah, at present, my only two issues (which I suppose are more **feature requests**) is that hallway connections overlap into the room, and the mask does not know which side is connected to a room.

**Comment by Moolt** [comment]
Usually hallways should not overlap with your room.
![casdfpture](https://user-images.githubusercontent.com/5003354/43611811-abcf8b96-96aa-11e8-9d15-7ab7bb2da429.PNG)
In the example screenshot you see that there usually should be no grid nodes inside or on the edges of the room (The only exception is the door-node, so hallways can connect to your room). I have no clue why this won't work for you and it's hard to figure out without taking a direct look at your project. This may or may not be a bug on my part, but as I said, I can't really tell.

> and the mask does not know which side is connected to a room.

This feature would be quite easy to implement, but it wouldn't really help you until hallways are generated properly.

**Comment by VoidFletcher** [comment]
Drop me an email, Dylan@DeeplinkStudios.com and we can organize project files.

In the meantime I'll begin an upload, as well as fiddle around some more, I'm hoping I removed the wrong component or something stupid like that.

Thanks again for all the help! :D 

I was thinking about how you said by default it doesn't overlap. So I went an enabled one of the room templates to allow it into generation, and then I disabled the assets within the hallways:

![image](https://user-images.githubusercontent.com/10835605/43615002-00cd92ea-96b6-11e8-8994-96120565161a.png)


They're not overlapping, right? That's not true though, watch what happens when I enable the assets within abstract bounds:

![image](https://user-images.githubusercontent.com/10835605/43615180-c24ac046-96b6-11e8-818a-f3001e3a4070.png)

I'll mess around with things before I go to bed, we'll talk tomorrow when you're free.

**Comment by VoidFletcher** [comment]
+Dies from lack of sleep.+

I finally figured it out, Moolt. I was an idiot and had the chunk's mesh collider deactivated. So I enabled it and the hallways are no longer generating through the chunks.

Regarding hallway overlap at the door, I increased the abstract bounds and created a small edge that doesn't extend all the way to the door (so that that lines up with the edge of the hallways.

![image](https://user-images.githubusercontent.com/10835605/43618566-5956a844-96c9-11e8-9744-0699be0ea188.png)

And as you know, the hallway masks don't know which side they connect to a room. So on the outside of the hallways and doors, I created kind of detector blocks... Okay that's putting it mildly. 

I have colliders that proceed to destroy every collider they come in contact with, before destroying themselves. It's an incredibly jank solution but it works :D 

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class collisionDestruction : MonoBehaviour {

	// When the script starts, it begins by starting a self-destruct co-routine to prevent any race conditions.
	void Start()
	{
		StartCoroutine(DestroyTick());

	}

	// For the brief time that the script is active, is deletes any gameObjects that are within contact of itself, thus
	// clearning a path.
	void OnCollisionEnter(Collision collisionObject)
	{
		print (collisionObject.collider.gameObject.name + " destroyed by path clearing script");
		Destroy (collisionObject.collider.gameObject);

	}

	// This is the self destruct co-routine mentioned in the start of the script.
	IEnumerator DestroyTick()
	{
		yield return new WaitForSeconds(1);
		Destroy(gameObject);
	}
}`

Before hitting play:
![image](https://user-images.githubusercontent.com/10835605/43618642-d8555e60-96c9-11e8-9d0a-73245b2cda11.png)

After hitting play:
![image](https://user-images.githubusercontent.com/10835605/43618668-fd1b185c-96c9-11e8-8700-6f88f1de38dd.png)

So now I need to create a script, that every time it generated a new level, it disabled the chunk colliders, as well as the hallway colliders and mesh renderers.

Speaking of generating a new level.... Do you have a method I can call to generate a new map at runtime?

Regardless, send me that email - would like to connect and stay in contact.

**Comment by Moolt** [comment]
> I finally figured it out, Moolt. I was an idiot and had the chunk's mesh collider deactivated. So I enabled it and the hallways are no longer generating through the chunks.

Nice, this looks way better now.

> Regarding hallway overlap at the door, I increased the abstract bounds and created a small edge that doesn't extend all the way to the door (so that that lines up with the edge of the hallways.

Good workaround. I added a new feature on hallway masks, so that you now can match for door segments. The blue box will match for a door segment. You may want to activate ``Make center non affecting`` so that the segment right in front of the door can still be filled by other masks after your door-mask has been applied. I will upload it soon.

![new segment](https://user-images.githubusercontent.com/5003354/43661176-90ecc48a-9761-11e8-818b-88c29709c7be.PNG)

![hallway door new](https://user-images.githubusercontent.com/5003354/43661373-3cc2bb16-9762-11e8-8209-587df34e1372.PNG)

You may need to add a tag to your door-hallway-mask to use it in a constraint. This way you can ensure that the mask is always used when it matches.

![door constraints](https://user-images.githubusercontent.com/5003354/43661389-5822e1b0-9762-11e8-8025-2f5738f1a515.PNG)

> Speaking of generating a new level.... Do you have a method I can call to generate a new map at runtime?

Theres a script called ``Level Generation Helper``. Just place it on a ``GameObject`` in the scene and it will generate a level on start.

> So now I need to create a script, that every time it generated a new level, it disabled the chunk colliders, as well as the hallway colliders and mesh renderers.

You could call this in the ``Level Generation Helper`` to disable ``MeshRenderer`` and ``MeshCollider`` Components.

```csharp    
 private void DisableCollidersAndMeshes()
    {
        var objects = GameObject.FindGameObjectsWithTag("ChunkInstance").ToList();
        foreach(GameObject go in objects)
        {
            var collider = go.GetComponent<MeshCollider>();
            var renderer = go.GetComponent<MeshRenderer>();
            collider.enabled = false;
            renderer.enabled = false;
        }
    }
```

> Regardless, send me that email - would like to connect and stay in contact.

malteweiss(at)yahoo.de

**Comment by VoidFletcher** [comment]
Well... :O 

So much for my elegant +cough+ shit +cough+ workaround. You good sir, are an absolute legend! I am speechless, thank you so much! :D 

I'll make all the relevant changes in the project now :D WHOO HOOO!
